/**
 * ScentraVN Serenity — Model Cards
 *
 * Transparent, honest documentation of every ML/heuristic model in the app:
 * what it does, what data it was trained on, real-world accuracy, and limits.
 * Values mirror the validation JSONs produced by the python/ pipelines.
 */

(() => {
  'use strict';

  const MODEL_CARDS = [
    {
      id: 'emotion',
      name: 'Emotion Valence (EEG)',
      icon: 'fa-face-smile-beam',
      task: 'Klasifikasi emosi: Positif / Netral / Negatif',
      input: 'EEG Muse (4 channel) → 15 fitur band-power + statistik',
      trainedOn: 'birdy654/eeg-brainwave-dataset-feeling-emotions (Muse, 2132 sampel)',
      accuracy: 0.93,
      accuracyLabel: '93% (compact, real Muse)',
      ceiling: 0.985,
      validation: 'Holdout real Muse EEG',
      grade: 'real',
      strengths: 'Dilatih & divalidasi pada hardware Muse yang sama dengan produk. Akurasi tinggi.',
      limits: 'Hanya valence kasar (3 kelas), bukan emosi spesifik. Sensitif kualitas sinyal.',
    },
    {
      id: 'mentalState',
      name: 'Mental State (EEG)',
      icon: 'fa-face-smile',
      task: 'Klasifikasi: Fokus / Netral / Rileks',
      input: 'EEG Muse (4 channel) → 15 fitur',
      trainedOn: 'birdy654/eeg-brainwave-dataset-mental-state (Muse, 2479 sampel)',
      accuracy: 0.72,
      accuracyLabel: '72% (compact, real Muse)',
      ceiling: 0.968,
      validation: 'Holdout real Muse EEG',
      grade: 'real',
      strengths: 'Data nyata dari Muse. Fokus & rileks terdeteksi baik.',
      limits: 'Kelas "netral" lebih sulit (~60% F1). Versi penuh 988-fitur capai 97% tapi tidak bisa dihitung live.',
    },
    {
      id: 'sleep',
      name: 'Sleep Stager (EEG)',
      icon: 'fa-moon',
      task: 'Klasifikasi 5 stage: Wake / N1 / N2 / N3 / REM',
      input: 'EEG frontal → band-power proportions',
      trainedOn: 'Sleep-EDF (PhysioNet, 197 subjek, 28k epoch)',
      accuracy: 0.60,
      accuracyLabel: '60% (subject-wise, real)',
      ceiling: null,
      validation: 'Subject-wise holdout (tanpa kebocoran antar subjek)',
      grade: 'real',
      strengths: 'Validasi ketat subject-wise pada data klinis nyata. Realistis untuk single-channel consumer.',
      limits: 'Single-channel frontal terbatas (~60% adalah ceiling wajar). N1 & REM paling sulit. Bukan PSG klinis.',
    },
    {
      id: 'edaStress',
      name: 'Stress (EDA/Keringat)',
      icon: 'fa-hand-sparkles',
      task: 'Klasifikasi: Tenang / Stress',
      input: 'EDA (GSR) + suhu kulit → 9 fitur statistik',
      trainedOn: 'WESAD (15 subjek, Empatica E4)',
      accuracy: 0.77,
      accuracyLabel: '77% (subject-wise, real)',
      ceiling: 0.74,
      validation: 'Subject-wise holdout',
      grade: 'real',
      strengths: 'EDA adalah penanda stres simpatik yang kuat. Sensor cocok dengan smartwatch ScentraVN (EDA+MLX temp).',
      limits: 'Recall stress ~47% (banyak false negatif). EDA terpengaruh aktivitas & suhu lingkungan.',
    },
    {
      id: 'stress',
      name: 'Stress (PPG/HRV)',
      icon: 'fa-heart-pulse',
      task: 'Klasifikasi: Normal / Stress',
      input: 'PPG → HRV (HR, SDNN, RMSSD, pNN50)',
      trainedOn: 'chtalhaanwar/mental-stress-ppg (54 sampel)',
      accuracy: 0.64,
      accuracyLabel: '64% (real, dataset kecil)',
      ceiling: null,
      validation: 'Holdout',
      grade: 'real-weak',
      strengths: 'Data nyata; lebih baik dari tebakan acak.',
      limits: 'Dataset sangat kecil (54 sampel) → confidence di-cap. Perlu data lebih banyak.',
    },
    {
      id: 'stressEEG',
      name: 'Stress (EEG)',
      icon: 'fa-brain',
      task: 'Indeks stres dari rasio theta/beta',
      input: 'EEG Muse → theta/beta ratio',
      trainedOn: 'Heuristik QEEG (threshold literatur)',
      accuracy: null,
      accuracyLabel: 'Heuristik QEEG',
      ceiling: null,
      validation: 'Berbasis literatur, belum divalidasi internal',
      grade: 'advisory',
      strengths: 'Theta/beta ratio penanda arousal yang dikenal di QEEG.',
      limits: 'Threshold tetap, bukan model terlatih. Sebaiknya dipakai bersama emotion/EDA.',
    },
    {
      id: 'cogLoad',
      name: 'Cognitive Load (EEG)',
      icon: 'fa-gauge-high',
      task: 'Klasifikasi: Ringan / Optimal / Berlebih',
      input: 'EEG frontal → 15 fitur',
      trainedOn: 'STEW Workload (Emotiv 14ch → mapped ke Muse frontal)',
      accuracy: 0.29,
      accuracyLabel: '29% subject-independent / 61% subject-dependent',
      ceiling: 0.607,
      validation: 'Subject-wise (29%) vs random (61%)',
      grade: 'advisory',
      strengths: 'Fitur membawa sinyal workload (61% subject-dependent).',
      limits: 'TIDAK generalisasi antar orang (29%, mendekati chance). Cross-hardware (Emotiv→Muse). Hanya advisory, jangan diandalkan.',
    },
    {
      id: 'glucose',
      name: 'Blood Glucose (PPG)',
      icon: 'fa-droplet',
      task: 'Estimasi gula darah (mg/dL)',
      input: 'PPG morphology + HRV + demografi',
      trainedOn: 'ppg-blood-sugar (22 pasien)',
      accuracy: null,
      accuracyLabel: 'R² ≈ 0 → fallback heuristik',
      ceiling: null,
      validation: 'Group K-Fold',
      grade: 'heuristic',
      strengths: 'Tersedia sebagai estimasi kasar.',
      limits: 'Model tidak unggul dari menebak rata-rata (data 22 pasien). Bukan alat medis. Jangan untuk keputusan kesehatan.',
    },
    {
      id: 'bp',
      name: 'Blood Pressure (PPG)',
      icon: 'fa-stethoscope',
      task: 'Estimasi tekanan darah (mmHg)',
      input: 'PPG pulse transit time + augmentation index',
      trainedOn: 'Heuristik literatur (Salamea-Palacios 2025, dll)',
      accuracy: null,
      accuracyLabel: 'Heuristik · research-grade',
      ceiling: null,
      validation: 'Tidak divalidasi pada pengguna',
      grade: 'heuristic',
      strengths: 'Memberi gambaran tren kasar.',
      limits: 'Estimasi eksperimental. Bukan pengganti tensimeter. MAE literatur ~8-12 mmHg.',
    },
    {
      id: 'hemoglobin',
      name: 'Hemoglobin (PPG)',
      icon: 'fa-droplet',
      task: 'Estimasi kadar Hb (g/dL) — skrining anemia',
      input: 'PPG multi-wavelength morphology',
      trainedOn: 'Literatur (multi-wavelength PPG, Nature 2026)',
      accuracy: null,
      accuracyLabel: 'Heuristik · MAE literatur ~8.5 g/L',
      ceiling: null,
      validation: 'Butuh PPG multi-panjang-gelombang (belum ada di MAX30102 2-λ)',
      grade: 'heuristic',
      strengths: 'Riset menunjukkan Hb bisa diperkirakan dari PPG multi-wavelength.',
      limits: 'MAX30102 hanya 2 wavelength (red+IR) → estimasi sangat kasar. Bukan diagnosis anemia.',
    },
    {
      id: 'uricAcid',
      name: 'Asam Urat',
      icon: 'fa-vial',
      task: 'Estimasi kadar asam urat (mg/dL)',
      input: 'Data klinis: usia, BMI, tekanan darah, pola makan',
      trainedOn: 'Literatur (Tlalpan 2020, clinical features)',
      accuracy: null,
      accuracyLabel: 'Berbasis input klinis, BUKAN sensor',
      ceiling: null,
      validation: 'Tidak dapat dari PPG/EDA',
      grade: 'heuristic',
      strengths: 'Risiko asam urat bisa diperkirakan dari faktor gaya hidup.',
      limits: 'TIDAK bisa diukur dari sensor optik/EDA. Perlu input manual (usia, BMI, diet). Bukan tes lab.',
    },
  ];

  /* HRV / DSP components — not ML but worth documenting as "accurate" */
  const DSP_COMPONENTS = [
    { name: 'HRV (SDNN, RMSSD, pNN50)', note: 'Signal processing murni dari PPG — akurat (<3ms vs ECG di literatur).' },
    { name: 'Respiratory Rate', note: 'Modulasi amplitudo PPG — ±2-3 napas/menit.' },
    { name: 'Perfusion Index', note: 'Rasio AC/DC — definisi standar.' },
    { name: 'EEG Band Powers (FFT)', note: 'FFT realtime 4 channel Muse — akurat secara matematis.' },
    { name: 'Frontal Alpha Asymmetry', note: 'ln(α_AF8) − ln(α_AF7) — penanda mood literatur.' },
  ];

  const ModelCards = {
    all: MODEL_CARDS,
    dsp: DSP_COMPONENTS,
    get: (id) => MODEL_CARDS.find(m => m.id === id) || null,
    gradeMeta(grade) {
      return ({
        'real':       { label: 'Tervalidasi Data Nyata', color: '#10b981', icon: 'fa-circle-check' },
        'real-weak':  { label: 'Data Nyata (Terbatas)',   color: '#f59e0b', icon: 'fa-circle-exclamation' },
        'advisory':   { label: 'Advisory · Hati-hati',    color: '#f97316', icon: 'fa-triangle-exclamation' },
        'heuristic':  { label: 'Heuristik · Eksperimental',color: '#ef4444', icon: 'fa-flask' },
        'synthetic':  { label: 'Synthetic',               color: '#6366f1', icon: 'fa-cube' },
      })[grade] || { label: grade, color: '#64748b', icon: 'fa-circle' };
    }
  };

  if (typeof window !== 'undefined') window.ModelCards = ModelCards;
})();
